version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: kobi_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret_password
      POSTGRES_DB: kobi_os
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d kobi_os"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - hackathon_net

  api:
    build: .
    container_name: kobi_api
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - hackathon_net

  ui:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: kobi_ui
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - api
    networks:
      - hackathon_net

networks:
  hackathon_net:
    driver: bridge

volumes:
  postgres_data: